version: "3.3"
services:
  qr_api:
    build:
      context: ./QR_API
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
  proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./Nginx/default.conf  :/etc/nginx/conf.d/default.conf
      - ./Nginx/nginx.conf    :/etc/nginx/nginx.conf